### ISSUE TITLE
ERROR: ActiveRecord oracle_enhanced adapter could not load Oracle JDBC driver.

### ISSUE THREAD

**Issue by riprop** [rammpeter/Panorama#3] opened 2021-04-29 18:55 UTC
Hi,

thank you for this software.

I would like to try it, but I'm getting error (below) in the page (and also in CMD console). 

Install documentation doesn't mention installing OJDBC, so I just put ojdbc8.jar to the same folder where Panorama.war is and it didn't help.
APP: standalone .war 
OS: Windows 10
C:\d\papps-add_new\Panorama>java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

How to solve it? 
Thank you 

Error text:
ERROR: ActiveRecord oracle_enhanced adapter could not load Oracle JDBC driver. Please install ojdbc11.jar or ojdbc8.jar or ojdbc7.jar or ojdbc6.jar library. from C:/Users/usr_1/AppData/Local/Temp/jetty-0.0.0.0-8080-Panorama.war-_-any-7153127580311692024.dir/webapp/WEB-INF/gems/gems/activerecord-oracle_enhanced-adapter-6.1.4/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:48:in `<main>' from org/jruby/RubyKernel.java:974:in 
...

**Comment by rammpeter** [comment] 2021-04-30 09:00
I'll proceed in reconstructing the problem and fix it soon.

**Comment by rammpeter** [comment] 2021-04-30 12:20
Thanks again for your information about the issue.
The issue is fixed now with Panorama version 2.10.51 which is the current version for download.
The problem has been caused by incompatible class file version (55) in ojdbc11.jar which is not supported by Java 1.8 (only up to 52).
Solution was to remove ojdbc11.jar inside Panorama if Java 1.8 is detected and this way force usage of ojdbc8.jar.

**Closed by rammpeter** 2021-04-30 12:20 UTC
