### ISSUE TITLE
Kein Start von Panorama möglich

### ISSUE THREAD

**Issue by petersternwald** [rammpeter/panorama#20] opened 2024-03-01 06:33 UTC
Beim Start der neuesten Panorama.jar Version auf meinen Windows 11 Rechner kommt folgende Fehlermeldung:

Extracting files from C:/Users/peter.ostermann/Downloads/Panorama.jar to C:\Users\PETER~1.OST\AppData\Local\Temp\eac33ad4-15a4-4309-965f-96a4e9bd6745
java.io.IOException: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at JarMain.newFile(JarMain.java:194)
        at JarMain.unzip(JarMain.java:162)
        at JarMain.main(JarMain.java:61)

Meine aktuelle JAVA Version:

java version "1.8.0_401"
Java(TM) SE Runtime Environment (build 1.8.0_401-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.401-b10, mixed mode

Gruß Peter Ostermann

**Comment by nicof38** [comment] 2024-03-04 15:31
Hello.

If needed, I have the exact same error with 31 release:

java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:463)
        at java.base/java.io.File.getCanonicalPath(File.java:626)
        at JarMain.newFile(JarMain.java:194)
        at JarMain.unzip(JarMain.java:162)
        at JarMain.main(JarMain.java:61)

Feel free to send any debug release if you need further information

**Comment by rammpeter** [comment] 2024-03-04 17:35
This issue will be fixed in release 2.17.32.
Can you please acknowledge that the issue is really fixed at your environment.

**Comment by nicof38** [comment] 2024-03-04 17:49
Confirmed, working fine on my side. Thanks !

**Comment by rammpeter** [comment] 2024-03-04 20:15
Problem fixed

**Closed** 2024-03-04 20:14 UTC
